class AuthService{
    async login(email,senha){try{const uc=await auth.signInWithEmailAndPassword(email.trim().toLowerCase(),senha);const doc=await db.collection('usuarios').doc(uc.user.uid).get();if(!doc.exists){await auth.signOut();return{sucesso:false,erro:'Usuário não encontrado'}}const usuario={id:doc.id,...doc.data()};await db.collection('usuarios').doc(uc.user.uid).update({ultimoLogin:firebase.firestore.FieldValue.serverTimestamp()}).catch(()=>{});return{sucesso:true,usuario}}catch(e){return{sucesso:false,erro:this.traduzirErro(e.code)}}}
    async cadastrar(d){try{if(!d.nome||d.nome.length<3)return{sucesso:false,erro:'Nome inválido'};if(!d.email||!d.email.includes('@'))return{sucesso:false,erro:'Email inválido'};if(!d.senha||d.senha.length<6)return{sucesso:false,erro:'Senha mínima 6 caracteres'};const uc=await auth.createUserWithEmailAndPassword(d.email.trim().toLowerCase(),d.senha);const usuario={uid:uc.user.uid,nome:d.nome.trim(),email:d.email.trim().toLowerCase(),tipo:d.tipo||'profissional',celular:d.celular||'',cpf:d.cpf||'',profissao:d.profissao||'',experiencia:parseInt(d.experiencia)||0,habilidades:d.habilidades||'',fotoPerfil:'',score:0,avaliacoes:[],avaliacoesRecebidas:0,dataCriacao:firebase.firestore.FieldValue.serverTimestamp(),ativo:true};await db.collection('usuarios').doc(uc.user.uid).set(usuario);uc.user.sendEmailVerification().catch(()=>{});return{sucesso:true,usuario:{id:uc.user.uid,...usuario}}}catch(e){const u=auth.currentUser;if(u)try{await u.delete()}catch(ex){}return{sucesso:false,erro:this.traduzirErro(e.code)}}}
    async solicitarCodigoRecuperacao(email){try{const el=email.trim().toLowerCase();if(!el||!el.includes('@'))return{sucesso:false,erro:'Email inválido'};const snap=await db.collection('usuarios').where('email','==',el).get();if(snap.empty)return{sucesso:false,erro:'Email não cadastrado'};const doc=snap.docs[0];const codigo=Math.floor(100000+Math.random()*900000).toString();await db.collection('usuarios').doc(doc.id).update({codigoRecuperacao:codigo,codigoExpiracao:firebase.firestore.Timestamp.fromDate(new Date(Date.now()+30*60*1000))});try{await auth.sendPasswordResetEmail(el,{url:window.location.origin,handleCodeInApp:false})}catch(ex){}return{sucesso:true,mensagem:'Código gerado!',codigo:codigo,uid:doc.id}}catch(e){return{sucesso:false,erro:'Erro ao gerar código'}}}
    async verificarCodigoRecuperacao(uid,codigo){try{const doc=await db.collection('usuarios').doc(uid).get();if(!doc.exists)return{sucesso:false,erro:'Usuário não encontrado'};const d=doc.data();if(!d.codigoRecuperacao)return{sucesso:false,erro:'Nenhum código solicitado'};if(d.codigoExpiracao&&d.codigoExpiracao.toDate()<new Date()){await db.collection('usuarios').doc(uid).update({codigoRecuperacao:firebase.firestore.FieldValue.delete(),codigoExpiracao:firebase.firestore.FieldValue.delete()});return{sucesso:false,erro:'Código expirado'}}if(d.codigoRecuperacao!==codigo)return{sucesso:false,erro:'Código inválido'};return{sucesso:true,email:d.email}}catch(e){return{sucesso:false,erro:'Erro ao verificar'}}}
    async redefinirSenhaComCodigo(uid,codigo,novaSenha){try{const v=await this.verificarCodigoRecuperacao(uid,codigo);if(!v.sucesso)return v;if(!novaSenha||novaSenha.length<6)return{sucesso:false,erro:'Senha mínima 6 caracteres'};await db.collection('usuarios').doc(uid).update({codigoRecuperacao:firebase.firestore.FieldValue.delete(),codigoExpiracao:firebase.firestore.FieldValue.delete()});try{await auth.sendPasswordResetEmail(v.email,{url:window.location.origin,handleCodeInApp:false})}catch(ex){}return{sucesso:true,mensagem:'Código verificado!',email:v.email}}catch(e){return{sucesso:false,erro:'Erro ao redefinir'}}}
    async logout(){try{await auth.signOut();return{sucesso:true}}catch(e){return{sucesso:false,erro:e.message}}}
    onAuthStateChange(cb){return auth.onAuthStateChanged(async(user)=>{if(user){try{const doc=await db.collection('usuarios').doc(user.uid).get();if(doc.exists)cb({id:doc.id,...doc.data()});else cb(null)}catch(e){cb(null)}}else cb(null)})}
    traduzirErro(c){const e={'auth/email-already-in-use':'Email já cadastrado','auth/invalid-email':'Email inválido','auth/weak-password':'Senha muito fraca','auth/user-not-found':'Email não cadastrado','auth/wrong-password':'Senha incorreta','auth/invalid-credential':'Credenciais inválidas','auth/too-many-requests':'Muitas tentativas'};return e[c]||'Erro ao processar'}
}
const authService=new AuthService();
console.log('✅ AuthService carregado');
