class DatabaseService{
    async buscarUsuario(uid){try{const doc=await db.collection('usuarios').doc(uid).get();if(!doc.exists)return null;return{id:doc.id,...doc.data()}}catch(e){return null}}
    async buscarTodosUsuarios(){try{const snap=await db.collection('usuarios').get();const usuarios=[];snap.forEach(doc=>{const d=doc.data();if(d.ativo!==false)usuarios.push({id:doc.id,...d})});usuarios.sort((a,b)=>(a.nome||'').localeCompare(b.nome||''));return usuarios}catch(e){return[]}}
    async atualizarUsuario(uid,dados){try{await db.collection('usuarios').doc(uid).update({...dados,ultimaAtualizacao:firebase.firestore.FieldValue.serverTimestamp()});return{sucesso:true}}catch(e){return{sucesso:false,erro:e.message}}}
    async criarVaga(dados){try{const ref=await db.collection('vagas').add({...dados,dataCriacao:firebase.firestore.FieldValue.serverTimestamp(),ativa:true});return{sucesso:true,id:ref.id}}catch(e){return{sucesso:false,erro:e.message}}}
    async buscarVagas(){try{const snap=await db.collection('vagas').get();const vagas=[];snap.forEach(doc=>{const d=doc.data();if(d.ativa!==false)vagas.push({id:doc.id,...d})});vagas.sort((a,b)=>{const da=a.dataCriacao?.toDate?.()||new Date(0);const db2=b.dataCriacao?.toDate?.()||new Date(0);return db2-da});return vagas}catch(e){return[]}}
    async criarConexao(uid,aid){try{await db.collection('conexoes').add({usuarioId:uid,amigoId:aid,status:'pendente',dataCriacao:firebase.firestore.FieldValue.serverTimestamp()});return{sucesso:true}}catch(e){return{sucesso:false,erro:e.message}}}
    async buscarConexoes(uid){try{const snap=await db.collection('conexoes').get();const conexoes=[];snap.forEach(doc=>{const d=doc.data();if(d.usuarioId===uid||d.amigoId===uid)conexoes.push({id:doc.id,...d})});return conexoes}catch(e){return[]}}
    async avaliarUsuario(aid,aid2,nota,com){try{await db.collection('avaliacoes').add({avaliadorId:aid,avaliadoId:aid2,nota,comentario:com||'',dataCriacao:firebase.firestore.FieldValue.serverTimestamp()});const snap=await db.collection('avaliacoes').get();const avs=[];snap.forEach(doc=>{const d=doc.data();if(d.avaliadoId===aid2)avs.push(d)});if(avs.length>0){const t=avs.length;const s=avs.reduce((a,b)=>a+b.nota,0);const sc=Math.round((s/t)*10)/10;await db.collection('usuarios').doc(aid2).update({score:sc,avaliacoesRecebidas:t})}return{sucesso:true}}catch(e){return{sucesso:false,erro:e.message}}}
}
const databaseService=new DatabaseService();
console.log('✅ DatabaseService carregado');
