class DatabaseService{
    async buscarUsuario(uid){try{const doc=await db.collection('usuarios').doc(uid).get();return doc.exists?{id:doc.id,...doc.data()}:null}catch(e){return null}}
    async buscarTodosUsuarios(){try{const snap=await db.collection('usuarios').get();const u=[];snap.forEach(doc=>{const d=doc.data();if(d.ativo!==false)u.push({id:doc.id,...d})});u.sort((a,b)=>(a.nome||'').localeCompare(b.nome||''));return u}catch(e){return[]}}
    async atualizarUsuario(uid,dados){try{await db.collection('usuarios').doc(uid).update({...dados,ultimaAtualizacao:firebase.firestore.FieldValue.serverTimestamp()});return{sucesso:true}}catch(e){return{sucesso:false,erro:e.message}}}
    async criarVaga(dados){try{const ref=await db.collection('vagas').add({...dados,dataCriacao:firebase.firestore.FieldValue.serverTimestamp(),ativa:true});return{sucesso:true,id:ref.id}}catch(e){return{sucesso:false,erro:e.message}}}
    async buscarVagas(){try{const snap=await db.collection('vagas').get();const v=[];snap.forEach(doc=>{const d=doc.data();if(d.ativa!==false)v.push({id:doc.id,...d})});v.sort((a,b)=>{(b.dataCriacao?.toDate?.()||new Date(0))-(a.dataCriacao?.toDate?.()||new Date(0))});return v}catch(e){return[]}}
    async buscarConexoes(uid){try{const snap=await db.collection('conexoes').get();const c=[];snap.forEach(doc=>{const d=doc.data();if(d.usuarioId===uid||d.amigoId===uid)c.push({id:doc.id,...d})});return c}catch(e){return[]}}
    async avaliarUsuarioCompleto(dados){try{const existente=await db.collection('avaliacoes').where('avaliadorId','==',dados.avaliadorId).where('avaliadoId','==',dados.avaliadoId).get();if(!existente.empty)return{sucesso:false,erro:'Você já avaliou este usuário'};await db.collection('avaliacoes').add(dados);const snap=await db.collection('avaliacoes').where('avaliadoId','==',dados.avaliadoId).get();const avs=[];snap.forEach(doc=>avs.push(doc.data()));if(avs.length>0){const total=avs.length;const soma=avs.reduce((a,b)=>a+b.nota,0);const score=Math.round((soma/total)*10)/10;await db.collection('usuarios').doc(dados.avaliadoId).update({score,avaliacoesRecebidas:total})}return{sucesso:true}}catch(e){return{sucesso:false,erro:e.message}}}
}
const databaseService=new DatabaseService();
console.log('✅ DatabaseService carregado');
